import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// import the library
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// import your icons
import { faChevronRight } from '@fortawesome/free-solid-svg-icons';


export default function Home() {


  


  return (

    
    <div className={styles.container}>
      <Head>
        <title>Salomon Sanchez - Diseño UX/UI en Figma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/salo-favicon.ico" />
      </Head>
      <div className={styles.circle_left}></div>
      <div className={styles.circle_right}></div>

      <header className={styles.header}>
        <div className={styles.contenedor}>
          <div className={styles.navBar}>
            <div className={styles.logo}><Image src="/img/logo-salo.svg" width={30} height={46}   /><span>Salomon Sanchez</span></div>
            <div className={styles.menu}>
              <ul className={styles.menu_ul}>
                <li className={styles.nav_links}>
                  <a className={styles.a_links} href="#">Cursos</a>
                </li>
                <li className={styles.nav_links}>
                  <a className={styles.a_links} href="#">Portafolio</a>
                </li>
                <li className={styles.nav_links}>
                  <a className={styles.a_links} href="#">Blog</a>
                </li>
                <li className={styles.nav_links}>
                  <a className={styles.a_links} href="#">Mentorías</a>
                </li>
              </ul>
            </div>
            <div className={styles.social_links}>
              <div className={styles.redes}>
                <a className={styles.redes_a} href="#">
                <Image src="/img/twitter-icon.svg"  width={36} height={29}  />
                </a>
                <a className={styles.redes_a} href="#">
                <Image src="/img/dribbble-icon.svg"  width={35} height={35}  />
                </a>
              </div>
              <div className={styles.suscribe}>
                <a href="#">
                  Suscríbete
                  <FontAwesomeIcon icon={faChevronRight} />
                </a> 
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title_home}>Full-Stack Designer<br></br>
& Content Creator</h1>
        <p className={styles.description}>Siempre llevar la usabilidad y la funcionalidad con una buena<br></br> estética es el resultado esperado.</p>
       
        <div className={styles.boton_full}>
          <a href="#" className={styles.boton_purple}>
              VER CURSO GRATIS
              <FontAwesomeIcon icon={faChevronRight} />
          </a> 
        </div>

        <div className={styles.recent}>
          <div className={styles.zoom1} >
            <Image src="/img/project-3.png" width={1280} height={720} />
          </div>
          <div className={styles.zoom3} >
            <Image src="/img/project-1.png" width={1280} height={720}/>
          </div>
          <div className={styles.zoom2} >
            <Image src="/img/project-2.png" width={1280} height={720}/>
          </div>
        </div>
       
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
